# Materials and Methods

## Experimental Design

### Neuronal cultures
Wild-type pregnant rats were euthanized by exposure to CO2 and soaked in 70% ethanol for 5 min for sterilization.
Embryonic day 16 (E16) rat fetuses were removed under sterile conditions and kept in phosphate-buffered saline (PBS) on ice. Basal forebrains were dissected and dissociated in serum-free medium (SFM) composed of a 1:1 mixture of Eagle’s MEM and Ham’s F-12 supplemented with insulin (2.5μg/ml), glucose (6 mg/ml), transferrin (100 μg/ml), putrescine (60 μm), progesterone (20 nm), selenium (30 nm), penicillin (0.5 U/ml), and streptomycin (0.5 μg/ml). The cells were then plated in microfluidic chambers (50) attached to glass coverslips in tissue culture dishes that were precoated overnight with poly-d-lysine (0.2 mg/ml). Two hundred microliters of medium was added to the soma compartment, and 100 μl of medium was maintained in the axon compartments to maintain a
medium volume difference that facilitated the growth of the axons
of the neurons through the microgrooves toward the axon compartment. The cells were maintained with the volume difference
between the soma and axon compartments in SFM supplemented
with 1% B-27 for 5 days at 37°C to obtain compartmentalized
BFCN cultures that could be treated separately at the axons or
somas. For biochemical experiments, BFCNs were plated on the
top compartment of filter inserts with a pore size of 1 μm, allowing neurites to grow through the filter to the bottom compartment,
providing an axon-enriched compartment for axon- or soma-specific
stimulation (51).

## Statistical Analysis
